### PR TITLE
Add neovim LSP styling for diagnostics

### PR DESCRIPTION
**Pull request by psoots**
Neovim is coming out with built-in support for language servers (v0.5). This addition sets default colors for the diagnostics output (errors and warnings and such provided by the language server). 

Attached is a picture of rust code using the summerfruit light theme in neovim with these changes applied.
screenshot-2021-Jan-20--07-57-08

### CODE REVIEW

**Comment by fnune** [comment]
I'd be interested in merging this on my fork: https://github.com/fnune/base16-fzf

Would you submit the PR there again?

**Comment by psoots** [comment]
@fnune This PR is only for supporting responses from a [language server](https://microsoft.github.io/language-server-protocol/). It doesn't really apply for FZF.

**Comment by fnune** [comment]
Oh... I linked the wrong repo. Here's the fork: https://github.com/fnune/base16-vim/

Editing my original comment.

**Comment by fnune** [comment]
Resubmitted and merged here https://github.com/fnune/base16-vim/pull/11

**Comment by entropitor** [comment]
I see this PR was recently merged but these highlights have changed name again (see `help diagnostic-highlights`)

**Pull request merged**
